package lists

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// Add returns "rtm.lists.add" method instance.
func Add(timeline string, name string, filter string) *methods.Method {
	name := "rtm.lists.add"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("name", name)
	p.Add("filter", filter)
	
	return &methods.Method{Name: name, Params: p}
}
