package lists

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// SetName returns "rtm.lists.setName" method instance.
func SetName(timeline string, listID string, name string) *methods.Method {
	name := "rtm.lists.setName"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("name", name)
	
	return &methods.Method{Name: name, Params: p}
}
