package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// Add returns "rtm.tasks.add" method instance.
func Add(timeline string, listID string, name string, parse string, parentTaskID string) *methods.Method {
	name := "rtm.tasks.add"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("name", name)
	p.Add("parse", parse)
	p.Add("parent_task_id", parentTaskID)
	
	return &methods.Method{Name: name, Params: p}
}
