package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// AddTags returns "rtm.tasks.addTags" method instance.
func AddTags(timeline string, listID string, taskseriesID string, taskID string, tags string) *methods.Method {
	name := "rtm.tasks.addTags"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	p.Add("tags", tags)
	
	return &methods.Method{Name: name, Params: p}
}
