package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// GetList returns "rtm.tasks.getList" method instance.
func GetList(listID string, filter string, lastSync string, callback string) *methods.Method {
	name := "rtm.tasks.getList"

	p := url.Values{}
	p.Add("method", name)
	p.Add("list_id", listID)
	p.Add("filter", filter)
	p.Add("last_sync", lastSync)
	p.Add("callback", callback)
	
	return &methods.Method{Name: name, Params: p}
}
