package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// NotesAdd returns "rtm.tasks.notes.add" method instance.
func NotesAdd(timeline string, listID string, taskseriesID string, taskID string, noteTitle string, noteText string) *methods.Method {
	name := "rtm.tasks.notes.add"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	p.Add("note_title", noteTitle)
	p.Add("note_text", noteText)
	
	return &methods.Method{Name: name, Params: p}
}
