package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// NotesEdit returns "rtm.tasks.notes.edit" method instance.
func NotesEdit(timeline string, noteID string, noteTitle string, noteText string) *methods.Method {
	name := "rtm.tasks.notes.edit"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("note_id", noteID)
	p.Add("note_title", noteTitle)
	p.Add("note_text", noteText)
	
	return &methods.Method{Name: name, Params: p}
}
