package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// SetDueDate returns "rtm.tasks.setDueDate" method instance.
func SetDueDate(timeline string, listID string, taskseriesID string, taskID string, due string, hasDueTime string, parse string) *methods.Method {
	name := "rtm.tasks.setDueDate"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	p.Add("due", due)
	p.Add("has_due_time", hasDueTime)
	p.Add("parse", parse)
	
	return &methods.Method{Name: name, Params: p}
}
