package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// SetParentTask returns "rtm.tasks.setParentTask" method instance.
func SetParentTask(timeline string, parentTaskID string, listID string, taskseriesID string, taskID string) *methods.Method {
	name := "rtm.tasks.setParentTask"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("parent_task_id", parentTaskID)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	
	return &methods.Method{Name: name, Params: p}
}
