package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// SetLocation returns "rtm.tasks.setLocation" method instance.
func SetLocation(timeline string, listID string, taskseriesID string, taskID string, locationID string) *methods.Method {
	name := "rtm.tasks.setLocation"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	p.Add("location_id", locationID)
	
	return &methods.Method{Name: name, Params: p}
}
