package tasks

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// SetStartDate returns "rtm.tasks.setStartDate" method instance.
func SetStartDate(timeline string, listID string, taskseriesID string, taskID string, start string, hasStartTime string, parse string) *methods.Method {
	name := "rtm.tasks.setStartDate"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("list_id", listID)
	p.Add("taskseries_id", taskseriesID)
	p.Add("task_id", taskID)
	p.Add("start", start)
	p.Add("has_start_time", hasStartTime)
	p.Add("parse", parse)
	
	return &methods.Method{Name: name, Params: p}
}
