package contacts

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// Add returns "rtm.contacts.add" method instance.
func Add(timeline string, contact string) *methods.Method {
	name := "rtm.contacts.add"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("contact", contact)
	
	return &methods.Method{Name: name, Params: p}
}
