package auth

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// CheckToken returns "rtm.auth.checkToken" method instance.
func CheckToken(authToken string) *methods.Method {
	name := "rtm.auth.checkToken"

	p := url.Values{}
	p.Add("method", name)
	p.Add("auth_token", authToken)
	
	return &methods.Method{Name: name, Params: p}
}
