package transactions

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// Undo returns "rtm.transactions.undo" method instance.
func Undo(timeline string, transactionID string) *methods.Method {
	name := "rtm.transactions.undo"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("transaction_id", transactionID)
	
	return &methods.Method{Name: name, Params: p}
}
