package groups

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// AddContact returns "rtm.groups.addContact" method instance.
func AddContact(timeline string, groupID string, contactID string) *methods.Method {
	name := "rtm.groups.addContact"

	p := url.Values{}
	p.Add("method", name)
	p.Add("timeline", timeline)
	p.Add("group_id", groupID)
	p.Add("contact_id", contactID)
	
	return &methods.Method{Name: name, Params: p}
}
