package groups

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// GetList returns "rtm.groups.getList" method instance.
func GetList() *methods.Method {
	name := "rtm.groups.getList"

	p := url.Values{}
	p.Add("method", name)
	
	return &methods.Method{Name: name, Params: p}
}
