package timelines

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// Create returns "rtm.timelines.create" method instance.
func Create() *methods.Method {
	name := "rtm.timelines.create"

	p := url.Values{}
	p.Add("method", name)
	
	return &methods.Method{Name: name, Params: p}
}
