package reflection

// This file is generated by methodGenerator.
// DO NOT MOTIFY THIS FILE.

import (
	"net/url"

	"github.com/kawaken/go-rtm/methods"
)

// GetMethods returns "rtm.reflection.getMethods" method instance.
func GetMethods() *methods.Method {
	name := "rtm.reflection.getMethods"

	p := url.Values{}
	p.Add("method", name)
	
	return &methods.Method{Name: name, Params: p}
}
